### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by mamidon** [lachlansneff/Metal#5]
I saw your blog post and thought this was an interesting project.  I'm curious what relationship this has with HTTP & browsers e.g.

are we writing a new browser stack for this; or using an existing browser engine?  are we simply providing an execution environment for webassembly code, but with a different run time environment than what would typically be found in a browser?

Also, is there somewhere to actually discuss things like this?  It seems like opening an 'issue' is a bit heavy, I've not really contributed to open source software before.

**Comment by rivertam** [comment]
I'm not a contributor yet, but I think at this stage, issues are appropriate for this kind of conversation.

As I understand it, the project aims to be an execution for web assembly, *not* a browser. I envision this being something like an OS that is like a browser but not a browser. Interested to hear what @lachlansneff has to say about it.

**Comment by lachlansneff** [comment]
@rivertam is correct. The intent is to execute web assembly, not to be a browser.

In the blog post, I put that in because I thought it would be something cool that *might* be possible, not that I necessarily wanted to implement it.

At the moment, the only browser-like thing will be its ability to execute wasm.

I created #MetalOS channel on freenode if you want to chat there.

**Comment by rivertam** [comment]
Just an update: We're on the gitter now (I believe in exclusion to IRC)

https://gitter.im/metal-os/Lobby
